auth-server: http://localhost:8894/auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8082
  servlet:
    context-path: /
spring:
  application:
    name: client2
  thymeleaf:
    cache: false
    prefix: classpath:templates
    suffix: .html
    mode: HTML
security:
  oauth2:
    client:
      client-id: client
      client-secret: 123456
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      user-info-uri: ${auth-server}/user
